---
title: "課堂練習"
date: "01/09/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(reticulate)
use_python("/Users/tim/anaconda3/envs/myEnvironment",
           required = T)
use_condaenv("myEnvironment", required = T)
```

```{r}
conda_install("myEnvironment","scikit-learn")
conda_install("myEnvironment","h2o")
```

```{python}
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import math # 用math.mathfunction：non vectorized function
from numpy.random import default_rng
# 8.8 randon number generator
# g_rv = defaut_rng() # to initiate a generator object
from scipy.linalg import inv, solve, det, eig

```

```{python}
## choose your model class
from sklearn.linear_model import LinearRegression, Ridge, RidgeCV, Lasso, LassoCV, SGDRegressor

## choose your metrics
from sklearn.metrics import mean_squared_error, r2_score

## training-test split
from sklearn.model_selection import train_test_split
```

```{python}
import numpy as np                                     
import matplotlib.pyplot as plt      
rng=np.random.default_rng(seed=2019) # initiate a random generator with seed 2019, for replication purpose
x = rng.normal(size=3000)

y = 0 +0.1* x + 0.33*rng.normal(size=x.shape)    


X=np.column_stack(
  (np.ones(x.shape),x,x**2,x**3)
)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)
```

#model setup
```{python}
# Linear regression
Linear1=LinearRegression()
# Ridge regression
Ridge1=Ridge(alpha=0.5)
Ridge2=RidgeCV(alphas=np.linspace(0.1,3,10), cv=5) # 5-fold cv ＃alphas選擇具有確定性，可能會有誤差
# Lasso regression
Lasso1=Lasso(alpha=0.5)
Lasso2=LassoCV(alphas=np.linspace(0.1,3,10), cv=5) # 5-fold cv
# SGD regression
SGD1=SGDRegressor()
SGD2=SGDRegressor()
```


# train
```{python}
# Linear regression
Linear1.fit(X_train,y_train)

Ridge1.fit(X_train,y_train)

Ridge2.fit(X_train,y_train) # 5-fold cv

Lasso1.fit(X_train,y_train)

Lasso2.fit(X_train,y_train) # 5-fold cv

SGD1.fit(X_train,y_train)


# partial fit 應該要讓整個epoch跑完三組
n_batches = 3
(n, m)=X_train.shape
split_index=np.arange(0,n,1)
rng.shuffle(split_index) # 洗牌
for slice_index in np.array_split(split_index, n_batches):
    SGD2.partial_fit(X_train[slice_index,:],y_train[slice_index])
```

```{python}
# Linear regression
y_predictLinear1=Linear1.predict(X_test)
# Ridge regression
y_predictRidge1=Ridge1.predict(X_test)
y_predictRidge2=Ridge2.predict(X_test) # 5-fold cv
# Lasso regression
y_predictLasso1=Lasso1.predict(X_test)
y_predictLasso2=Lasso2.predict(X_test) # 5-fold cv
# SGD regression
y_predictSGD1=SGD1.predict(X_test)
y_predictSGD2=SGD2.predict(X_test)
```

```{python}
mseLinear1=mean_squared_error(y_test,y_predictLinear1)
# Ridge regression
mseRidge1=mean_squared_error(y_test,y_predictRidge1)
mseRidge2=mean_squared_error(y_test,y_predictRidge2) # 5-fold cv ＃最小
# Lasso regression
mseLasso1=mean_squared_error(y_test,y_predictLasso1)
mseLasso2=mean_squared_error(y_test,y_predictLasso2) # 5-fold cv
# SGD regression
mseSGD1=mean_squared_error(y_test,y_predictSGD1)
mseSGD2=mean_squared_error(y_test,y_predictSGD2)
```

