---
title: "課堂練習"
date: "12/05/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(reticulate)
use_python("/Users/tim/anaconda3/envs/myEnvironment",
           required = T)
use_condaenv("myEnvironment", required = T)
```

```{r}
conda_install("myEnvironment","scipy")
```

#BayesianTheorem

```{python}
import numpy as np
import pandas as pd
```

```{python}
Suppose there are only two possible p values: 0.1 and 0.3. What would be the likelihood value of a sample with 50 heads and 50 tails?
import scipy.stats as stat
bin_1=stat.binom(n=100,p=0.1)
like_1=bin_1.pmf(50) # Likelihood(p=0.1)

bin_3=stat.binom(n=100,p=0.3)
like_3=bin_3.pmf(50) # Likelihood(p=0.3)
```

```{python}
#scaled posterior
posterior_sc_1 = like_1*0.3
posterior_sc_3 = like_3*0.7

sum13 = posterior_sc_1+posterior_sc_3
posterior1 = posterior_sc_1/sum13
posterior3 = posterior_sc_3/sum13

```


#randomState
```{python}
import numpy.random as rs_rv

sdN=rs_rv.standard_normal(size=10)# RandomState所產生的10個standard normal random number

sdN.reshape(2,5)
```

```{python}
rs_rv.choice(
 a=[1,0],
 size=100,
 replace= True,
 p=[0.1,0.9]
)
```

##seed

```{python}
rs_rv.seed(2019)
rs_rv.standard_normal(size=10)
```


#generator
```{python}
from numpy.random import default_rng

g_rv=default_rng() #  g_rv為Generator object
g_rv.standard_normal(size=10) # Generator所產生的standard normal random number
```

##seed
```{python}
g_rv=default_rng(2019) # 需要在建立Generator obj時就設好
g_rv.standard_normal(size=10)
```

#practice
```{python}
(x1,ep1)=g_rv.standard_normal(size=(2,100)) #packing

x=g_rv.standard_normal(100)
ep=g_rv.standard_normal(100)
```

```{python}
y=0.1*x + 0.33*ep
```

#OOP
```{python}
class YellowRectangle:
    """ A Python object that describes the properties of a yellow rectangle """
    color="yellow" 
    
    def __init__(self, width, height):
        self.width = width
        self.height = height
    
    def __repr__(self):
        return "Rectangle(width={w}, height={h})".format(h=self.height, w=self.width)
        
    def compute_area(self):
        return self.width * self.height

```

```{python}
YR=YellowRectangle # YR is a class object
yr1=YR(5,10) # yr1 is an instance
yr1.color
yr1.width
print(yr1)
type(yr1)
isinstance(yr1, YellowRectangle)
isinstance(YellowRectangle, YellowRectangle)

yr2=YellowRectangle(1,3)
yr2.compute_area()
YR(5,10)

```

```{python}
class linFamily:
    surname="林"
    def __init__(self, firstname, gender):
        self.firstname = firstname
        self.gender = gender
    def __repr__(self):
        return "我叫{X}, 性別{Y}".format(X=self.surname+ self.firstname, Y= self.gender)
        
linFamily("小巴","男")
```

##class method
```{python}
class Family:
    surname=""
    def __init__(self, firstname, gender):
        self.firstname = firstname
        self.gender = gender
    def __repr__(self):
        return "我叫{X}, 性別{Y}".format(X=self.surname+ self.firstname, Y= self.gender)
    @classmethod #declaration "cls" 避免cls命名重複
    def new(cls, newsurname): # class method 為了只更動surname
        cls.surname=newsurname
        return cls
```

```{python}
#新的class
wangFamily = Family.new("王")
#新的instance
wang1= wangFamily("小明","男")

wang1
wang1.surname
```


#missing value
```{python}
import numpy as np
import numpy.ma as ma
x = np.array([1, 2, 3, -1, 5])
```

```{python}
mx = ma.masked_array(x, mask=[0, 0, 0, 1, 0])
mx
mx.mean()
```


```{python}
dictionaryA={
  "日期": [2001,2002,2003],
  "金額": [21000,33000,45880]}
dictionaryA

dictionaryA["數量"]=[100,200,300]
dictionaryA
```

