---
title: "課堂練習"
date: "9/12/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(reticulate)
use_python("/Users/tim/anaconda3/envs/myEnvironment",
           required = T)
use_condaenv("myEnvironment", required = T)
```


# 2.3.1

```{python}
dictionaryA={
  "日期": [2001,2002,2003],
  "金額": [21000,33000,45880]}
dictionaryA

dictionaryA["數量"]=[100,200,300] #增加元素
dictionaryA
```


```{python}
dictionaryA["金額"]

dictionaryA.keys()

dictionaryA.values()

dictionaryA.items()

```

```{python}

dictionaryA.items()[0]

list(dictionaryA.items())[0]
```


```{python}
dictionaryA.get("日期")
dictionaryA.get("品項")
dictionaryA.get("品項","無此key")
```

```{python}
"日期" in dictionaryA
"學號" in dicdictionaryA
```

# 硬轉dictionary成list 會只存key
```{python}
list(dictionaryA)
```


# 找出dict_finStatement中’營業利益（損失）‘為負的’公司名稱’
```{python}
import pandas as pd

finStatement=pd.read_csv("http://mopsfin.twse.com.tw/opendata/t187ap06_O_ci.csv")
dict_finStatement=finStatement.to_dict()
```

```{python}
type(dict_finStatement)
```

```{python}
dict_finStatement.keys()
```

# 在R裡面看python物件
```{r}
library(dplyr)
py$dict_finStatement %>% View
```

# list comprehension + if
```{python}
[ 
  dict_finStatement["公司名稱"][i]  for i in range(len(dict_finStatement["營業利益（損失）"] )) 
  if  dict_finStatement["營業利益（損失）"][i] < 0
  ]
```

##老師解法
先找出index

```{python}
profit = list(dict_finStatement["營業利益（損失）"].values())
profitLoss = [profit[i] for i in range(len(profit)) if profit[i] <0]
lossFirmKeys=[i for i in range(len(profit)) if profit[i] <0]
```

再取出來
```{python}
lossCompany=[dict_finStatement["公司名稱"].get(i) for i in lossFirmKeys]
```

```{python}
{
  lossCompany[i]:profitLoss[i] for i in range(len(lossCompany))
} 
```




#ch3 function(已內縮取function 內容)
```{python}
def myFun(x,y):
  z = x+y
  return z

```

```{python}
myFun(0,3)
```

```{python}
def myFun3(x,y=6): #預設值
  z = x+y
  return z

myFun3(3)
myFun3(3,5)
myFun3(y=5, x=3)
```


```{python}
def test2(input1,*input3):
  print('input1 is ', input1)
  print('input3 is ', input3)
  return None
 
test2(1,1.2,4,5)
test2(1,[1.2,4],5)
test2(["1","b"],{2,5,7},10)
```


# unpacking usage
*可以用在input arguments, 它代表unpacking
```{python}
def f(a,b,c):
   return a+b+c


f(1,3,4)
f(*[1,3],4)
f(1,*[3,4])
f(*[1,3,4])
```

```{python}
from math import * # 引進數學

def normal_pdf(z,mu,sigma):
  return 1/(sqrt(2*pi*sigma**2))*exp(-(z-mu)**2/(2*sigma**2))

normal_pdf(0.8,0,1)
```

```{python}
def utility_cobb_douglass(x,y,alpha=1,beta=3):
  
  utilValue = x**alpha*y**beta # 程序產生output值
  
  return utilValue # 傳回output值

utility_cobb_douglass(1,1,0.5,0.5)
utility_cobb_douglass(1,1)
```

```{python}
def utility_cobb_douglass1(x,y,**parameters): #硬性規定使用者需要specify alpha,beta
  alpha=parameters["alpha"]
  beta=parameters["beta"]
  utilValue = x**alpha*y**beta # 程序產生output值
  
  return utilValue # 傳回output值
```

```{python}
utility_cobb_douglass1(1,1)
utility_cobb_douglass1(1,2,alpha=2,beta=2)

```

```{python}
dic1={
  "1":"000",
  "2":2
}
```

# 需要小心global值會被改變
```{python}
global1=[1,3,[4,5]]
def funtest(x):
  x[0]="a"  #深層復制
  y=x[:]
  y[1]="b"
  y[2][1]="c" #淺複製，但[4,5]的儲存位置和global1一樣，所以會被改變
  return None

global1
funtest(global1)
global1
```

